---
dune:2.5--gcc:
  image: duneci/dune:2.5
  script:
  - dunecontrol --current all
  - dunecontrol --current make test

dune:git--gcc:
  image: duneci/dune:git
  script:
  - dunecontrol --current all
  - dunecontrol --current make test

dune:git--clang:
  image: duneci/dune:git
  script:
  - CMAKE_FLAGS="-DCMAKE_CXX_COMPILER=/usr/bin/clang++" dunecontrol --current all
  - dunecontrol --current make test
